name: Generate RSS Feeds

on:
  schedule:
    - cron: '5 7 * * *'  # Runs once a day
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 feedgenerator requests sendgrid

    - name: Ensure directories exist
      run: |
        mkdir -p data feeds docs

    - name: Generate feeds  
      run: |
        python src/app.py https://bigsister.live/blog
        python src/app.py https://ollama.com/blog

    - name: Commit and push RSS feed to GitHub Pages
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        # Copy generated RSS files to docs folder
        cp feeds/*xml docs/
        
        # Set up feed headers
        echo "/*xml" > docs/_headers
        echo "  Content-Type: application/rss+xml; charset=utf-8" >> docs/_headers
        
        # Commit the changes
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/* feeds/* docs/*xml docs/_headers
        git commit -m 'Update RSS feeds'
        
        # Pull latest changes before pushing to avoid conflicts
        git pull --rebase origin main
        
        # Push the changes back to the repository
        git push https://${{ secrets.PAT }}@github.com/jljarvi/genrss.git main

    - name: Send email notification
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        python <<EOF
        import os
        import sendgrid
        from sendgrid.helpers.mail import Mail, Email, To, Content

        sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
        from_email = Email("admin@nfld.uk")
        to_email = To("jljarvi@pm.me")
        subject = "RSS Feeds Generated"
        content = Content("text/plain", "The RSS feeds has been successfully generated and are now live on GitHub Pages.")
        mail = Mail(from_email, to_email, subject, content)

        response = sg.client.mail.send.post(request_body=mail.get())
        print(response.status_code)
        print(response.body)
        print(response.headers)
        EOF
